"""Pydantic schemas for the sentinel hierarchical stock selection system."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================

class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertCategory(str, Enum):
    MARKET_RISK = "market_risk"
    SECTOR_FLOW = "sector_flow"
    TECHNICAL = "technical"
    VOLUME = "volume"
    NEWS = "news"
    CAPITAL = "capital"
    RPS = "rps"
    FINANCIAL = "financial"
    POOL_CHANGE = "pool_change"


class MarketRegime(str, Enum):
    BULL = "bull"
    BEAR = "bear"
    CONSOLIDATION = "consolidation"
    TRANSITION_UP = "transition_up"
    TRANSITION_DOWN = "transition_down"


class ActionType(str, Enum):
    BUY = "buy"
    SELL = "sell"
    ADD_POSITION = "add_position"
    REDUCE_POSITION = "reduce_position"
    WATCH = "watch"
    HOLD = "hold"
    AVOID = "avoid"


# =============================================================================
# Tier 1: Sentinel Alert (Bottom → Mid)
# =============================================================================

class SentinelAlert(BaseModel):
    """Alert generated by a Data Sentinel when anomaly detected."""
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    sentinel_type: str = ""
    category: AlertCategory = AlertCategory.TECHNICAL
    severity: AlertSeverity = AlertSeverity.WARNING
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())

    # Target identification
    ts_code: str | None = None
    sector_code: str | None = None
    index_code: str | None = None

    # Alert content
    signal_type: str = ""
    description: str = ""
    metric_name: str = ""
    metric_value: float = 0
    threshold: float = 0
    deviation_pct: float = 0

    # Context for analyst
    context: dict[str, Any] = Field(default_factory=dict)


# =============================================================================
# Tier 2: Analyst Report (Mid → Top)
# =============================================================================

class AnalystInsight(BaseModel):
    """Single insight from analyst's cross-signal analysis."""
    insight_type: str = ""
    description: str = ""
    confidence: float = 0.0
    supporting_alerts: list[str] = Field(default_factory=list)
    related_stocks: list[str] = Field(default_factory=list)


class StockSignal(BaseModel):
    """Individual stock signal in analyst report."""
    ts_code: str
    stock_name: str = ""
    action: ActionType = ActionType.WATCH
    confidence: float = 0.0
    reasons: list[str] = Field(default_factory=list)
    entry_price: float | None = None
    stop_loss: float | None = None
    target_price: float | None = None


class AnalystReport(BaseModel):
    """Report generated by Analyst when multiple sentinel alerts form a pattern."""
    report_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    analyst_type: str = ""
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    trigger_count: int = 0

    # Synthesized view
    market_regime: MarketRegime | None = None
    sector_view: dict[str, str] = Field(default_factory=dict)
    stock_signals: list[StockSignal] = Field(default_factory=list)

    # Insights
    insights: list[AnalystInsight] = Field(default_factory=list)

    # Raw alerts that triggered this report
    source_alerts: list[SentinelAlert] = Field(default_factory=list)

    # Recommendation strength
    overall_conviction: float = 0.0


# =============================================================================
# Tier 3: Investment Decision (Top → User)
# =============================================================================

class SectorAllocation(BaseModel):
    sector_name: str
    sector_code: str = ""
    weight_suggestion: float = 0.0
    reason: str = ""
    momentum: str = "neutral"


class StockAction(BaseModel):
    ts_code: str
    stock_name: str = ""
    action: ActionType
    urgency: str = "normal"
    position_size: float = 0.0
    entry_price: float | None = None
    stop_loss: float | None = None
    target_price: float | None = None
    reasons: list[str] = Field(default_factory=list)
    confidence: float = 0.0
    sector: str = ""


class InvestmentDecision(BaseModel):
    """Final investment decision from the Investment Director (LLM-driven)."""
    decision_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    trade_date: str = ""

    # Market-level
    market_regime: MarketRegime = MarketRegime.CONSOLIDATION
    market_risk_level: str = "normal"
    suggested_total_position: float = 1.0

    # Sector
    favored_sectors: list[SectorAllocation] = Field(default_factory=list)
    avoided_sectors: list[str] = Field(default_factory=list)

    # Stock actions
    buy_candidates: list[StockAction] = Field(default_factory=list)
    sell_candidates: list[StockAction] = Field(default_factory=list)
    watch_list: list[StockAction] = Field(default_factory=list)

    # Narratives (LLM-generated)
    market_narrative: str = ""
    sector_narrative: str = ""
    stock_narrative: str = ""
    timing_narrative: str = ""

    # Meta
    source_reports: list[str] = Field(default_factory=list)
    confidence: float = 0.0


# =============================================================================
# System Status
# =============================================================================

class SentinelSystemStatus(BaseModel):
    is_running: bool = False
    last_cycle_at: str | None = None
    sentinels_active: int = 0
    analysts_active: int = 0
    alerts_today: int = 0
    reports_today: int = 0
    decisions_today: int = 0
    message_bus_metrics: dict[str, Any] = Field(default_factory=dict)
    last_decision: InvestmentDecision | None = None
